# SPDX-License-Identifier: LGPL-2.1-or-later
#
# Copyright (C) 2021, 2022 Collabora Limited
# Author: Guillaume Tucker <guillaume.tucker@collabora.com>

trees:

  kernelci:
    url: "https://github.com/kernelci/linux.git"

  mainline:
    url: 'https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git'


build_environments:

  gcc-10:
    cc: gcc
    cc_version: 10
    arch_params:
      x86_64:
        name: 'x86'


build_variants:
  variants: &build-variants
    gcc-10:
      build_environment: gcc-10
      architectures:
        x86_64:
          base_defconfig: 'x86_64_defconfig'
          filters:
            - regex: { defconfig: 'x86_64_defconfig' }


build_configs:

  kernelci_staging-mainline:
    tree: kernelci
    branch: 'staging-mainline'
    variants: *build-variants

  kernelci_staging-next:
    tree: kernelci
    branch: 'staging-next'
    variants: *build-variants

  kernelci_staging-stable:
    tree: kernelci
    branch: 'staging-stable'
    variants: *build-variants

  mainline:
    tree: mainline
    branch: 'master'
    variants: *build-variants


db_configs:

  docker-host:
    db_type: kernelci_api
    url: http://172.17.0.1:8001

  staging.kernelci.org:
    db_type: kernelci_api
    url: https://staging.kernelci.org:9000


labs:

  k8s-gke-eu-west4:
    lab_type: kubernetes
    context: 'gke_android-kernelci-external_europe-west4-c_kci-eu-west4'

  shell:
    lab_type: shell


test_plans:

  fstests-base: &fstests-base
    pattern: 'fstests.jinja2'
    params: &fstests-base-params
      njobs: 4

  fstests-base-gce: &fstests-base-gce
    <<: *fstests-base
    params: &fstests-base-params-gce
      <<: *fstests-base-params
      gce: True

  fstests-minimal-kvm:
    <<: *fstests-base
    params:
      <<: *fstests-base-params
      testcfg: '1k,4k'
      testcase: 'generic/001,generic/002'

  fstests-minimal-gce:
    <<: *fstests-base-gce
    params:
      <<: *fstests-base-params-gce
      testcfg: '1k,4k'
      testcase: 'generic/001,generic/002'

  fstests-smoke-kvm:
    <<: *fstests-base
    params:
      <<: *fstests-base-params
      testcfg: '4k'
      testgroup: 'quick'

  fstests-smoke-gce:
    <<: *fstests-base-gce
    params:
      <<: *fstests-base-params-gce
      testcfg: '4k'
      testgroup: 'quick'

  kunit:
    pattern: 'kunit.jinja2'
    image: 'kernelci/staging-gcc-10:x86-kunit-kernelci'

  kver:
    pattern: 'kver.jinja2'
    image: 'kernelci/staging-kernelci'


device_types:

  kubernetes:
    base_name: kubernetes
    class: kubernetes

  shell:
    base_name: shell
    class: shell
